import styles from './index.module.scss';
import type { Metadata } from 'next';
import { Fascinate_Inline } from 'next/font/google';
import { ReactNode } from 'react';
import { ThemeProvider } from 'next-themes';
import { StoreProvider } from '@/app/store-provider';
import clsx from 'clsx';

const FascinateInline = Fascinate_Inline({ weight: '400', preload: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = ({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) => {
  return (
    <html lang={params.locale}>
      <body className={FascinateInline.className}>
        <StoreProvider>
          <ThemeProvider defaultTheme="dark" enableSystem={false}>
            <main className={clsx(styles.main)}>{children}</main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
};
