import '../styles/themes/light.css';
import '../styles/themes/dark.css';
import '../styles/normalize.css';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import LanguageSwitcher from '@/shared/ui/LanguageSwitcher';
import Link from 'next/link';
import { Title } from '@/shared/ui/Title';
import { BackButton } from '@/shared/ui/BackButton';
import { ThemeProvider } from 'next-themes';
import { ThemeToggle } from '@/shared/ui/ThemeSwitch';
import { StoreProvider } from '@/app/store-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider enableSystem={false}>
            <main style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <LanguageSwitcher />
              <ThemeToggle />
              <Link href={`/${params.locale}`}>
                <Title dictionary="home" />
              </Link>

              <BackButton />

              {children}
            </main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
